all:
  hosts:
    mairie-dev:
      ansible_host: 51.158.96.108
      ansible_user: ubuntu
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_ssh_private_key_file: "~/.ssh/login_scaleway_mairie360"
      client_id: "mairie360-dev"
      repo_name: "Deploiment"