all:
  children:
    # --- VOTRE CHAÎNE INTERNE ---
    mairie360:
      children:
        mairie360_hub:
          hosts:
            argocd-hub:
              ansible_host: "212.47.242.79"
              argocd_domain: "argocd-hub.mairie360-eip.fr"
        mairie360_instances:
          hosts:
            mairie-dev:
              ansible_host: "IP_DE_VOTRE_MACHINE_DEV"
              target_hub_ip: "212.47.242.79"
            mairie-staging:
              ansible_host: "IP_DE_VOTRE_MACHINE_STAGING"
              target_hub_ip: "212.47.242.79"
            mairie-prod:
              ansible_host: "IP_DE_VOTRE_MACHINE_PROD"
              target_hub_ip: "212.47.242.79"

    # --- VOS CLIENTS (Exemple : Mairie de Paris) ---
    # mairie_paris:
    #   children:
    #     paris_hub:
    #       hosts:
    #         paris-argocd-hub:
    #           ansible_host: "IP_DE_MACHINE_HUB_PARIS"
    #     paris_instances:
    #       hosts:
    #         paris-instance:
    #           ansible_host: "IP_DE_MACHINE_INSTANCE_PARIS"

  # Variables communes à tout le monde (évite de répéter l'user et la clé)
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/login_scaleway_mairie360"
