all:
  children:
    # --- VOTRE CHAÎNE INTERNE ---
    mairie360:
      children:
        mairie360_hub:
          hosts:
            argocd-hub:
              ansible_host: "212.47.242.79"
              argocd_domain: "argocd-hub.mairie360-eip.fr"
        mairie360_instances:
          hosts:
            mairie-dev:
              ansible_host: "163.172.7.159"
              instance_domain: "dev.mairie360-eip.fr"
              argocd_domain: "argocd-hub.mairie360-eip.fr"
            mairie-staging:
              ansible_host: "195.154.157.114"
              instance_domain: "staging.mairie360-eip.fr"
              argocd_domain: "argocd-hub.mairie360-eip.fr"
            mairie-prod:
              ansible_host: "51.15.251.220"
              instance_domain: "prod.mairie360-eip.fr"
              argocd_domain: "argocd-hub.mairie360-eip.fr"

    # --- VOS CLIENTS (Exemple : Mairie de Paris) ---
    # mairie_paris:
    #   children:
    #     paris_hub:
    #       hosts:
    #         paris-argocd-hub:
    #           ansible_host: "IP_DE_MACHINE_HUB_PARIS"
    #     paris_instances:
    #       hosts:
    #         paris-instance:
    #           ansible_host: "IP_DE_MACHINE_INSTANCE_PARIS"

  # Variables communes à tout le monde (évite de répéter l'user et la clé)
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/login_scaleway_mairie360"
